# Generated by Django 3.1 on 2020-08-17 16:32

from django.db import migrations
import newapp.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20200817_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpage',
            name='content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('title_And_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=60, required=True, validators=[newapp.blocks.check_for_title])), ('text', wagtail.core.blocks.RichTextBlock(features=['p', 'bold', 'ol'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn Wagtail', max_length=40, required=True))]))], blank=True, null=True),
        ),
    ]
